#include: "otherfile.conf"
#include-toplevel: "otherfile.conf"
# The server clause sets the main parameters.
server:
	# verbosity number, 0 is least verbose. 1 is default.
	# verbosity: 1
	# number of threads to create. 1 disables threading.
	num-threads: 4
	interface: 192.168.1.3
	# port to answer queries from
	port: 53
	# NOTE: 32768-60999 is the ephemeral port range on Linux.
	outgoing-port-permit: 32768-60999
	do-ip4: yes
	do-ip6: yes
	do-udp: yes
	do-tcp: yes
	do-daemonize: yes
        access-control: 192.168.1.0/24 allow
	use-syslog: yes
	unwanted-reply-threshold: 10000000
	# NOTE: This file is provided by the dnssec-root package.
	trust-anchor-file: "/usr/share/dnssec-root/trusted-key.key"
	val-log-level: 1
	ede: yes
	ede-serve-expired: yes
	root-hints: "/etc/unbound/root.hints"


python:
	# Script file to load
	# python-script: "/ubmodule-tst.py"

# Dynamic library config section. To enable:
dynlib:
	# Script file to load
	# dynlib-file: "/dynlib.so"

# Remote control config section.
remote-control:
	# Enable remote control with unbound-control(8) here.
	control-enable: yes
	control-interface: /run/unbound.control.sock
include: "/etc/unbound/blacklist.conf"
include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"
